# Generated by Django 2.1.8 on 2019-05-26 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_initial_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formpage',
            name='reply_address',
            field=models.CharField(blank=True, help_text='Optional - to reply to the submitter, specify the email field here. For example, if a form field above is labeled "Your Email", enter: {{ your_email }}', max_length=255, verbose_name='Reply-to address'),
        ),
    ]
